// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1r8PB4HRRdIOzo3FPqTJ3dBEwCyKhxJQ',
    appId: '1:230224905462:web:d13739cb5c2f9a93d218d7',
    messagingSenderId: '230224905462',
    projectId: 'astratechtask',
    authDomain: 'astratechtask.firebaseapp.com',
    storageBucket: 'astratechtask.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPjYvT2ApQ0GkxBMv49fny93BrsCc5jBo',
    appId: '1:230224905462:android:5cbdacba5f1b1b98d218d7',
    messagingSenderId: '230224905462',
    projectId: 'astratechtask',
    storageBucket: 'astratechtask.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI1UbKnSHgxCEU8-xCB63paFbYQvJ7BEw',
    appId: '1:230224905462:ios:94677977718bdccfd218d7',
    messagingSenderId: '230224905462',
    projectId: 'astratechtask',
    storageBucket: 'astratechtask.appspot.com',
    iosClientId: '230224905462-haq7emtbreuog8eonkjdisjumu2diepg.apps.googleusercontent.com',
    iosBundleId: 'com.astratech.ahmedsaeedtask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI1UbKnSHgxCEU8-xCB63paFbYQvJ7BEw',
    appId: '1:230224905462:ios:e69aea7705cca0ebd218d7',
    messagingSenderId: '230224905462',
    projectId: 'astratechtask',
    storageBucket: 'astratechtask.appspot.com',
    iosClientId: '230224905462-5frva6qk1a2i79q7105fjnakucb5qs17.apps.googleusercontent.com',
    iosBundleId: 'com.astratech.ahmedsaeedtask.RunnerTests',
  );
}
